config/routes.rb
Rails.application.routes.draw do
  resources :hoges
  resources :people
  get 'items/list'

end

app/models/hoge.rb
class Hoge < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hoges_controller.rb
class HogesController < ApplicationController
  before_action :set_hoge, only: [:show, :edit, :update, :destroy]

  # GET /hoges
  # GET /hoges.json
  def index
    @hoges = Hoge.all
  end

  # GET /hoges/1
  # GET /hoges/1.json
  def show
  end

  # GET /hoges/new
  def new
    @hoge = Hoge.new
  end

  # GET /hoges/1/edit
  def edit
  end

  # POST /hoges
  # POST /hoges.json
  def create
    @hoge = Hoge.new(hoge_params)

    respond_to do |format|
      if @hoge.save
        format.html { redirect_to @hoge, notice: 'Hoge was successfully created.' }
        format.json { render :show, status: :created, location: @hoge }
      else
        format.html { render :new }
        format.json { render json: @hoge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hoges/1
  # PATCH/PUT /hoges/1.json
  def update
    respond_to do |format|
      if @hoge.update(hoge_params)
        format.html { redirect_to @hoge, notice: 'Hoge was successfully updated.' }
        format.json { render :show, status: :ok, location: @hoge }
      else
        format.html { render :edit }
        format.json { render json: @hoge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hoges/1
  # DELETE /hoges/1.json
  def destroy
    @hoge.destroy
    respond_to do |format|
      format.html { redirect_to hoges_url, notice: 'Hoge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hoge
      @hoge = Hoge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hoge_params
      params.require(:hoge).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def list
    Rails.logger.debug("before")
    a = 'hoge'
		raise 'ahhh!'
    binding.pry
    Rails.logger.debug("after")
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/hoges/_form.html.erb
<%= form_for(@hoge) do |f| %>
  <% if @hoge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hoge.errors.count, "error") %> prohibited this hoge from being saved:</h2>

      <ul>
      <% @hoge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hoges/edit.html.erb
<h1>Editing Hoge</h1>

<%= render 'form' %>

<%= link_to 'Show', @hoge %> |
<%= link_to 'Back', hoges_path %>

app/views/hoges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hoges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hoges.each do |hoge| %>
      <tr>
        <td><%= hoge.name %></td>
        <td><%= link_to 'Show', hoge %></td>
        <td><%= link_to 'Edit', edit_hoge_path(hoge) %></td>
        <td><%= link_to 'Destroy', hoge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hoge', new_hoge_path %>

app/views/hoges/new.html.erb
<h1>New Hoge</h1>

<%= render 'form' %>

<%= link_to 'Back', hoges_path %>

app/views/hoges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hoge.name %>
</p>

<%= link_to 'Edit', edit_hoge_path(@hoge) %> |
<%= link_to 'Back', hoges_path %>

app/views/items/list.html.erb
<h1>Items#list</h1>
<p>Find me in app/views/items/list.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApcRailsWs3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>